name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Install OpenSSL
      if: matrix.os == 'windows-latest'
      run: vcpkg install openssl:x64-windows
    - name: Set OpenSSL Env
      if: matrix.os == 'windows-latest'
      run: $env:OPENSSL_DIR = 'C:/vcpkg/packages/openssl_x86-windows/'
      
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: Swatinem/rust-cache@v1

    - name: build
      run: cargo build --release --verbose
